# Generated by Django 2.1.2 on 2021-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
