# Generated by Django 2.1.2 on 2021-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_auto_20210428_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('D', 'Double Occupancy'), ('T', 'Triple Occupancy'), ('F', 'Four Occupancy')], default=None, max_length=1),
        ),
    ]
